language: node_js
env:
- BITCOINDJS_ENV=test
node_js:
  - "0.12"
before_install:
  - git config --global user.email "dev@bitpay.com"
  - git config --global user.name "BitPay, Inc."
script:
  - _mocha -R spec integration/regtest.js
  - _mocha -R spec --recursive
