language: node_js
node_js:
  - '4.0'
before_install:
  - npm install -g bower
  - npm install -g grunt-cli
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - bower install
  - npm install
after_success:
  - npm run exec:coveralls
