version: 2.0
jobs:
  setup:
    docker:
      - image: circleci/python:2.7-node
    working_directory: ~/repo
    steps:
      - run:
          name: Install ZMQ
          command: sudo apt install -y libzmq3-dev
      - checkout
      - run:
          name: Delete uneeded packages
          command: cd packages && rm -rf insight-api insight-ui bitcore-wallet-service merit-rpc bitcore-node bitcore-p2p
      - restore_cache:
          keys:
            - bitcore-lib-deps-{{ checksum "packages/bitcore-lib/package.json" }}
      - restore_cache:
          keys:
            - bitcore-message-deps-{{ checksum "packages/bitcore-message/package.json" }}
      - restore_cache:
          keys:
            - bitcore-payment-protocol-deps-{{ checksum "packages/bitcore-payment-protocol/package.json" }}
      - restore_cache:
          keys:
            - lw-deps-{{ checksum "packages/lightwallet/package.json" }}
      - restore_cache:
          keys:
            - lw-desktop-deps-{{ checksum "packages/lightwallet/desktop/package.json" }}
      - restore_cache:
          keys:
            - lw-mobile-deps-{{ checksum "packages/lightwallet/mobile/package.json" }}
      - run:
          name: Install Lerna
          command: sudo npm i -g lerna
      - run: lerna bootstrap --concurrency=$(nproc)
      - save_cache:
          paths:
            - packages/bitcore-lib/node_modules
            - packages/bitcore-lib/package-lock.json
          key: bitcore-lib-deps-{{ checksum "packages/bitcore-lib/package.json" }}
      - save_cache:
          paths:
            - packages/bitcore-message/node_modules
            - packages/bitcore-message/package-lock.json
          key: bitcore-message-deps-{{ checksum "packages/bitcore-message/package.json" }}
      - save_cache:
          paths:
            - packages/bitcore-payment-protocol/node_modules
            - packages/bitcore-payment-protocol/package-lock.json
          key: bitcore-payment-protocol-deps-{{ checksum "packages/bitcore-payment-protocol/package.json" }}
      - save_cache:
          paths:
            - packages/lightwallet/node_modules
            - packages/lightwallet/package-lock.json
          key: lw-deps-{{ checksum "packages/lightwallet/package.json" }}
      - save_cache:
          paths:
            - packages/lightwallet/desktop/node_modules
            - packages/lightwallet/desktop/package-lock.json
          key: lw-desktop-deps-{{ checksum "packages/lightwallet/desktop/package.json" }}
      - save_cache:
          paths:
            - packages/lightwallet/mobile/node_modules
            - packages/lightwallet/mobile/package-lock.json
          key: lw-mobile-deps-{{ checksum "packages/lightwallet/mobile/package.json" }}
      - run:
          name: Setup LW Environment
          command: cd packages/lightwallet/common/environments && cp environment.example.ts enviornment.dev.ts
      - run:
          name: Unit tests
          command: cd packages/lightwallet && npm test
      - run:
          name: Build DLW
          command: cd packages/lightwallet && npm run build
      - run:
          name: Build MLW
          command: cd packages/lightwallet/desktop && npm run build
      - persist_to_workspace:
          root: ~/repo
          paths:
            - packages/lightwallet/mobile/www
            - packages/lightwallet/desktop/dist

  desktop_e2e:
    docker:
      - image: circleci/node:8
    working_directory: ~/
    steps:
      - attach_workspace:
          at: ~/repo/
      - run:
          name: Install http-server
          command: npm i -g spa-http-server
#      - run:
#          name: Serve DLW
#          command: http-server
#          background: true
#      - run:
#          name: Wait for Desktop LW app to be ready
#          command: wget --retry-connrefused --no-check-certificate -T 30 http://localhost:8888
#      - run: cd packages/lightwallet && npm run test:desktop:e2e

  mobile_e2e:
    docker:
      - image: circleci/node:8
    working_directory: ~/
    steps:
      - attach_workspace:
          at: ~/repo/
      - run:
          name: Install http-server
          command: npm i -g spa-http-server
#      - run:
#          name: Serve MLW
#          command: http-server
#      - run:
#          name: Wait for Mobile LW app to be ready
#          command: wget --retry-connrefused --no-check-certificate -T 30 http://localhost:8100
#      - run: cd ~/repo/packages/lightwallet && npm run test:mobile:e2e

workflows:
  version: 2
  build:
    jobs:
      - setup
      - desktop_e2e:
          requires:
            - setup
      - mobile_e2e:
          requires:
            - setup
