version: 2.0
jobs:
  setup:
    docker:
      - image: circleci/python:2.7-node
    working_directory: ~/repo
    steps:
      - run:
          name: Install ZMQ
          command: sudo apt install -y libzmq3-dev
      - checkout
      - restore_cache:
          keys:
            - bitcore-lib-deps-{{ checksum "packages/bitcore-lib/package.json" }}
      - restore_cache:
          keys:
            - bitcore-message-deps-{{ checksum "packages/bitcore-message/package.json" }}
      - restore_cache:
          keys:
            - bitcore-node-deps-{{ checksum "packages/bitcore-node/package.json" }}
      - restore_cache:
          keys:
            - bitcore-p2p-deps-{{ checksum "packages/bitcore-p2p/package.json" }}
      - restore_cache:
          keys:
            - bitcore-payment-protocol-deps-{{ checksum "packages/bitcore-payment-protocol/package.json" }}
      - restore_cache:
          keys:
            - bitcore-wallet-service-deps-{{ checksum "packages/bitcore-wallet-service/package.json" }}
      - restore_cache:
          keys:
            - insight-api-deps-{{ checksum "packages/insight-api/package.json" }}
      - restore_cache:
          keys:
            - insight-ui-deps-{{ checksum "packages/insight-ui/package.json" }}
      - restore_cache:
          keys:
            - lw-deps-{{ checksum "packages/lightwallet/package.json" }}
      - restore_cache:
          keys:
            - lw-desktop-deps-{{ checksum "packages/lightwallet/desktop/package.json" }}
      - restore_cache:
          keys:
            - lw-mobile-deps-{{ checksum "packages/lightwallet/mobile/package.json" }}
      - restore_cache:
          keys:
            - merit-rpc-deps-{{ checksum "packages/merit-rpc/package.json" }}
      - run:
          name: Install Lerna
          command: sudo npm i -g lerna
      - run: lerna bootstrap --concurrency=$(nproc)
      - save_cache:
          paths:
            - packages/bitcore-lib/node_modules
            - packages/bitcore-lib/package-lock.json
          key: bitcore-lib-deps-{{ checksum "packages/bitcore-lib/package.json" }}
      - save_cache:
          paths:
            - packages/bitcore-message/node_modules
            - packages/bitcore-message/package-lock.json
          key: bitcore-message-deps-{{ checksum "packages/bitcore-message/package.json" }}
      - save_cache:
          paths:
            - packages/bitcore-node/node_modules
            - packages/bitcore-node/package-lock.json
          key: bitcore-node-deps-{{ checksum "packages/bitcore-node/package.json" }}
      - save_cache:
          paths:
            - packages/bitcore-p2p/node_modules
            - packages/bitcore-p2p/package-lock.json
          key: bitcore-p2p-deps-{{ checksum "packages/bitcore-p2p/package.json" }}
      - save_cache:
          paths:
            - packages/bitcore-payment-protocol/node_modules
            - packages/bitcore-payment-protocol/package-lock.json
          key: bitcore-payment-protocol-deps-{{ checksum "packages/bitcore-payment-protocol/package.json" }}
      - save_cache:
          paths:
            - packages/bitcore-wallet-service/node_modules
            - packages/bitcore-wallet-service/package-lock.json
          key: bitcore-wallet-service-deps-{{ checksum "packages/bitcore-wallet-service/package.json" }}
      - save_cache:
          paths:
            - packages/insight-api/node_modules
            - packages/insight-api/package-lock.json
          key: insight-api-deps-{{ checksum "packages/insight-api/package.json" }}
      - save_cache:
          paths:
            - packages/insight-ui/node_modules
            - packages/insight-ui/package-lock.json
          key: insight-ui-deps-{{ checksum "packages/insight-ui/package.json" }}
      - save_cache:
          paths:
            - packages/lightwallet/node_modules
            - packages/lightwallet/package-lock.json
          key: lw-deps-{{ checksum "packages/lightwallet/package.json" }}
      - save_cache:
          paths:
            - packages/lightwallet/desktop/node_modules
            - packages/lightwallet/desktop/package-lock.json
          key: lw-desktop-deps-{{ checksum "packages/lightwallet/desktop/package.json" }}
      - save_cache:
          paths:
            - packages/lightwallet/mobile/node_modules
            - packages/lightwallet/mobile/package-lock.json
          key: lw-mobile-deps-{{ checksum "packages/lightwallet/mobile/package.json" }}
      - save_cache:
          paths:
            - packages/merit-rpc/node_modules
            - packages/merit-rpc/package-lock.json
          key: merit-rpc-deps-{{ checksum "packages/merit-rpc/package.json" }}

      - persist_to_workspace:
          root: ~/repo
          paths:
            - packages/bitcore-lib
            - packages/lightwallet

  unit_test:
    docker:
      - image: circleci/node:8
    working_directory: ~/
    steps:
      - attach_workspace:
          at: ~/repo/
      - run: cd repo/packages/lightwallet && npm test

  desktop_e2e:
    docker:
      - image: circleci/node:8
    working_directory: ~/
    steps:
      - attach_workspace:
          at: ~/repo/
      - run:
          name: Run ng-serve
          command: cd ~/repo/packages/lightwallet/desktop && npm start
          background: true
      - run:
          name: Wait for Desktop LW app to be ready
          command: wget --retry-connrefused --no-check-certificate -T 30 http://localhost:8888
      - run: cd packages/lightwallet && npm run test:desktop:e2e

  mobile_e2e:
    docker:
      - image: circleci/node:8
    working_directory: ~/
    steps:
      - attach_workspace:
          at: ~/repo/
      - run:
          name: Run ionic serve
          command: cd ~/repo/packages/lightwallet && npm run ionic:serve
          background: true
      - run:
          name: Wait for Mobile LW app to be ready
          command: wget --retry-connrefused --no-check-certificate -T 30 http://localhost:8100
      - run: cd ~/repo/packages/lightwallet && npm run test:mobile:e2e

  build_dlw:
    docker:
      - image: circleci/node:8
    working_directory: ~/
    steps:
      - attach_workspace:
          at: ~/repo/
      - run: cd ~/repo/packages/lightwallet && npm run build -- --prod

  build_mlw:
    docker:
      - image: circleci/node:8
    working_directory: ~/
    steps:
      - attach_workspace:
          at: ~/repo/
      - run: cd ~/repo/packages/lightwallet/desktop && npm run build:prod

workflows:
  version: 2
  build:
    jobs:
      - setup
      - unit_test:
          requires:
            - setup
      - desktop_e2e:
          requires:
            - setup
      - mobile_e2e:
          requires:
            - setup
      - build_dlw:
          requires:
            - setup
      - build_mlw:
          requires:
            - setup
